
services:
  gridtracker-to-discord:
    build: .
    container_name: gridtracker-to-discord
    ports:
      - "5000:5000"
      - "2237:2237/udp"
    volumes:
      - ./templates:/app/templates
      - ./.env:/app/.env
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - UDP_PORT=${UDP_PORT}
    restart: unless-stopped
